server:
  port: 8080
  

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/survey-app?useSSL=false
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true
    show-sql: true