server:
  port: 5000
  

spring:
  datasource:
    username: survey_app_admin
    password: SurveyAdminApp12345
    url: jdbc:mysql://survey-app.cqh0az309wia.ap-south-1.rds.amazonaws.com:3306/survey-app?useSSL=false
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true
    show-sql: true