server:
  port: 5000
  
overseas:
  app:
   jwt:
    issuer: "overseasapp"
    secret.key: "overseassecret"
  

spring:
  datasource:
    username: survey_app_admin
    password: sample
    url: http://localhost:3701
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true
    show-sql: true
